//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latihan_smk_nusantara_2017.data.source.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public @class()
        {
            this.detail_class = new HashSet<detail_class>();
            this.header_schedule = new HashSet<header_schedule>();
        }
    
        public string class_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<detail_class> detail_class { get; set; }
        public virtual ICollection<header_schedule> header_schedule { get; set; }
    }
}
