//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latihan_smk_nusantara_2017.data.source.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_class
    {
        public int detail_id { get; set; }
        public string class_id { get; set; }
        public int schedule_id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual header_schedule header_schedule { get; set; }
    }
}
