//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekolahApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class header_schedule
    {
        public header_schedule()
        {
            this.student_multi_schedule = new HashSet<student_multi_schedule>();
        }
    
        public int schedule_id { get; set; }
        public string subject_id { get; set; }
        public string teacher_id { get; set; }
        public string class_id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<student_multi_schedule> student_multi_schedule { get; set; }
    }
}
