//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekolahApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_multi_schedule
    {
        public int id { get; set; }
        public int schedule_id { get; set; }
        public string student_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual header_schedule header_schedule { get; set; }
    }
}
