//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekolahApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string no_hp { get; set; }
        public byte[] photo { get; set; }
        public int role_id { get; set; }
    }
}
